<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Safety" Id="{ffbfa9ce-8ba4-405c-8606-945cde52289d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FINAL FB_Safety
VAR_INPUT
	bEmergencyStopOK				AT%I*	: BOOL;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Safety">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>